### PR TITLE
feat: add angular submodule

### PR DESCRIPTION
**Pull request by noelle-jung**
Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by ShirwaM — APPROVED** [review]

**Review by ShirwaM — CHANGES_REQUESTED** [review]
It seems like the module link isn't showing up in the branch: https://github.com/googlemaps/on-demand-rides-deliveries-samples/tree/angular

do we need to specify a specific commit? @shawnlu-g 

https://github.com/googlemaps/on-demand-rides-deliveries-samples/commit/4bc2509e0e19722805a603f34349fb745d82ded2

**Comment by shawnlu-g** [comment]
Hi @ShirwaM 
When the Angular submodule was added was the command `git submodule add ...` or something else?

**Comment by noelle-jung** [comment]
Hi @shawnlu-g 

I added the Angular submodule with `git submodule add https://github.com/googlemaps/angular-on-demand-rides-deliveries-samples.git`

That modified .gitmodules to look like

```
[submodule "angular-on-demand-rides-deliveries-samples"]
	path = angular-on-demand-rides-deliveries-samples
	url = https://github.com/googlemaps/angular-on-demand-rides-deliveries-samples.git
```

which I changed manually to 

```
[submodule "angular"]
	path = angular
	url = https://github.com/googlemaps/angular-on-demand-rides-deliveries-samples
```
(changed path and removed ".git" from the url) to follow the convention of the other submodules in .gitmodules.

**Comment by shawnlu-g** [comment]
Sorry Noelle, I think something didn't go well during the process, may need to redo. I believe the key is the 2nd argument of the `git submodule add` command
Screen Shot 2022-04-28 at 10 23 16 AM

If you use 
```
git submodule add https://github.com/googlemaps/angular-on-demand-rides-deliveries-samples.git angular-js
``` 
it may work well.

**Comment by noelle-jung** [comment]
Thanks @shawnlu-g , I opened a new PR https://github.com/googlemaps/on-demand-rides-deliveries-samples/pull/7

**Pull request closed without merging**
